version: '3.9'
services:
    db:
        container_name: db
        image: postgres:14-bullseye
        restart: always
        environment:
            POSTGRES_PASSWORD: ${db_PASSWORD}
            POSTGRES_DB: ${db_DB}
            POSTGRES_USER: ${db_USER}
        ports:
            - 5432:5432
    server:
        container_name: server
        image: server:1.0
        build:
            context: ./server/
            dockerfile: ./Dockerfile
        command: ${server_CMD}
        ports:
            - 3000:3000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - db
        links:
            - "db:database"